### ISSUE TITLE
问题简介

### ISSUE THREAD

**Issue by chocolate-candy** [ymcui/Chinese-Minority-PLM#12]
您好，在复原例子的时候，确保了版本与您一样，但在终端运行的时候，出现了如下错误，暂时无法得到有效解决，请问是否可以帮忙看一下问题所在，十分打扰！

python run_finetune.py --params cino-params.json

Traceback (most recent call last):
  File "run_finetune.py", line 188, in <module>
    main()
  File "run_finetune.py", line 182, in main
    config = CINO_FT_Configer(load(args.hparam))
AttributeError: 'Namespace' object has no attribute 'hparam'

**Comment by GeekDream-x** [comment]
感谢您的反馈，问题已修复，请使用最新版示例代码试一下呢
