### ISSUE TITLE
gradient_acc参数

### ISSUE THREAD

**Issue by rela0426** [ymcui/Chinese-Minority-PLM#18]
能帮忙解释一下`gradient_acc`参数嘛
==loss /= self.config.gradient_acc==代码中，用到了`gradient_acc`参数，所以不太明白这句代码的意思。![在这里插入图片描述](https://img-blog.csdnimg.cn/49431c69e6f1434cb614357637381a50.png?x-oss-process=image/watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA77yCas-F77yzz4TjgII=,size_20,color_FFFFFF,t_70,g_se,x_16#pic_center)

**Comment by GeekDream-x** [comment]
你好，这个参数表示梯度累积的次数，帮助在计算资源（如显存）有限的情况下实现与较大batch size等价的训练过程。
