### ISSUE TITLE
Wiki-Chinese-Minority实验

### ISSUE THREAD

**Issue by Geministudents** [ymcui/Chinese-Minority-PLM#19]
你好，请问为什么说Wiki-Chinese-Minority实验中，除了中文以外的语种是zero-shot测试呢，这个预训练模型不是也包括了那些少数民族语言的么，不应该是finetune么

**Comment by airaria** [comment]
这个实验主要是验证CINO的cross-lingual zero-shot能力。你也可以在各个少数民族语言上finetune。

**Comment by Geministudents** [comment]
好的好的，感谢
