### ISSUE TITLE
best_cino.pth

### ISSUE THREAD

**Issue by tf302** [ymcui/Chinese-Minority-PLM#7]
求～ best_cino.pth 文件在哪？ 还是自己构建的

**Comment by GeekDream-x** [comment]
是您通过对CINO进行finetuning之后保存下来的最优模型参数文件，可在cino-params.json文件中自定义成您喜欢的名字。

**Comment by GeekDream-x** [comment]
> 求～ best_cino.pth 文件在哪？ 还是自己构建的

是您通过对CINO进行finetuning之后保存下来的最优模型参数文件，可在cino-params.json文件中自定义成您喜欢的名字。
